/**
 * Created by smohan on 2016/11/19.
 * Edit by vexpaer on 2022/9/11
 */
var songList = [
    { title:'A.M.7. - Welcome to New York (Big Apple Version).mp3',singer:'NULL',audio:'music/A.M.7. - Welcome to New York (Big Apple Version).mp3',thumbnail:'data/vexpaer.png' },
    { title:'advantage Lucy - Nico.mp3',singer:'NULL',audio:'music/advantage Lucy - Nico.mp3',thumbnail:'data/vexpaer.png' },
    { title:'AJR - 100 Bad Days.mp3',singer:'NULL',audio:'music/AJR - 100 Bad Days.mp3',thumbnail:'data/vexpaer.png' },
    { title:'AJR - 3 O‘Clock Things.mp3',singer:'NULL',audio:'music/AJR - 3 O‘Clock Things.mp3',thumbnail:'data/vexpaer.png' },
    { title:'AJR - Bang!.mp3',singer:'NULL',audio:'music/AJR - Bang!.mp3',thumbnail:'data/vexpaer.png' },
    { title:'AJR - Burn the House Down.mp3',singer:'NULL',audio:'music/AJR - Burn the House Down.mp3',thumbnail:'data/vexpaer.png' },
    { title:'AJR - No Grass Today.mp3',singer:'NULL',audio:'music/AJR - No Grass Today.mp3',thumbnail:'data/vexpaer.png' },
    { title:'AJR - Pretender (Acoustic).mp3',singer:'NULL',audio:'music/AJR - Pretender (Acoustic).mp3',thumbnail:'data/vexpaer.png' },
    { title:'AJR - The Entertainment‘s Here.mp3',singer:'NULL',audio:'music/AJR - The Entertainment‘s Here.mp3',thumbnail:'data/vexpaer.png' },
    { title:'AJR - World‘s Smallest Violin.mp3',singer:'NULL',audio:'music/AJR - World‘s Smallest Violin.mp3',thumbnail:'data/vexpaer.png' },
    { title:'AJR,Rivers Cuomo - Sober Up.mp3',singer:'NULL',audio:'music/AJR,Rivers Cuomo - Sober Up.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Alan Silvestri - The Avengers.mp3',singer:'NULL',audio:'music/Alan Silvestri - The Avengers.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Alan Walker,Coldplay - Hymn For The Weekend [Remix].mp3',singer:'NULL',audio:'music/Alan Walker,Coldplay - Hymn For The Weekend [Remix].mp3',thumbnail:'data/vexpaer.png' },
    { title:'Alan Walker,Noah Cyrus,Digital Farm Animals - All Falls Down.mp3',singer:'NULL',audio:'music/Alan Walker,Noah Cyrus,Digital Farm Animals - All Falls Down.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Alex Goot,Kurt Hugo Schneider,Megan Nicole - Stand By You.mp3',singer:'NULL',audio:'music/Alex Goot,Kurt Hugo Schneider,Megan Nicole - Stand By You.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Alexander Oscar - January.mp3',singer:'NULL',audio:'music/Alexander Oscar - January.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Alfie Templeman,Coach Party - My Best Friend.mp3',singer:'NULL',audio:'music/Alfie Templeman,Coach Party - My Best Friend.mp3',thumbnail:'data/vexpaer.png' },
    { title:'ALI,AKLO - LOST IN PARADISE.mp3',singer:'NULL',audio:'music/ALI,AKLO - LOST IN PARADISE.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Ana Zimmer - Underwater.mp3',singer:'NULL',audio:'music/Ana Zimmer - Underwater.mp3',thumbnail:'data/vexpaer.png' },
    { title:'André Rieu - Prelude – Act I (Carmen).mp3',singer:'NULL',audio:'music/André Rieu - Prelude – Act I (Carmen).mp3',thumbnail:'data/vexpaer.png' },
    { title:'AndyWho,Rajiv Dhall - Youth ( AndyWho Remix ).mp3',singer:'NULL',audio:'music/AndyWho,Rajiv Dhall - Youth ( AndyWho Remix ).mp3',thumbnail:'data/vexpaer.png' },
    { title:'Anthem Lights - Best of 2012： Payphone／Call Me Maybe／Wide Awake／Starship／We Are Young.mp3',singer:'NULL',audio:'music/Anthem Lights - Best of 2012： Payphone／Call Me Maybe／Wide Awake／Starship／We Are Young.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Anthem Lights - Best of 2014： Problem ／ Boom Clap ／ Rude ／ Am I Wrong ／ All About That Bass ／ All of Me ／ Chandelier ／ Blank Space ／ Not a Bad Thing ／ Happy.mp3',singer:'NULL',audio:'music/Anthem Lights - Best of 2014： Problem ／ Boom Clap ／ Rude ／ Am I Wrong ／ All About That Bass ／ All of Me ／ Chandelier ／ Blank Space ／ Not a Bad Thing ／ Happy.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Anthem Lights - Best of 2017 Medley.mp3',singer:'NULL',audio:'music/Anthem Lights - Best of 2017 Medley.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Anthem Lights - I Really Like You.mp3',singer:'NULL',audio:'music/Anthem Lights - I Really Like You.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Anthem Lights - One Direction Mash-Up 2.mp3',singer:'NULL',audio:'music/Anthem Lights - One Direction Mash-Up 2.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Anthem Lights - Treasure ／ When I Was Your Man.mp3',singer:'NULL',audio:'music/Anthem Lights - Treasure ／ When I Was Your Man.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Approaching Nirvana - You.mp3',singer:'NULL',audio:'music/Approaching Nirvana - You.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Aura Dione - Friends (Rock Mafia & David Jost Radio Mix).mp3',singer:'NULL',audio:'music/Aura Dione - Friends (Rock Mafia & David Jost Radio Mix).mp3',thumbnail:'data/vexpaer.png' },
    { title:'AURORA - Cure For Me.mp3',singer:'NULL',audio:'music/AURORA - Cure For Me.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Avicii - Waiting For Love.mp3',singer:'NULL',audio:'music/Avicii - Waiting For Love.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Avicii,Imagine Dragons - Heart Upon My Sleeve.mp3',singer:'NULL',audio:'music/Avicii,Imagine Dragons - Heart Upon My Sleeve.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Avicii,Martin Garrix,Simon Aldred - Waiting For Love.mp3',singer:'NULL',audio:'music/Avicii,Martin Garrix,Simon Aldred - Waiting For Love.mp3',thumbnail:'data/vexpaer.png' },
    { title:'AViVA - CEMETERY.mp3',singer:'NULL',audio:'music/AViVA - CEMETERY.mp3',thumbnail:'data/vexpaer.png' },
    { title:'AViVA - HOUDINI.mp3',singer:'NULL',audio:'music/AViVA - HOUDINI.mp3',thumbnail:'data/vexpaer.png' },
    { title:'AViVA - HYPNOTIZED.mp3',singer:'NULL',audio:'music/AViVA - HYPNOTIZED.mp3',thumbnail:'data/vexpaer.png' },
    { title:'AViVA - TWISTED.mp3',singer:'NULL',audio:'music/AViVA - TWISTED.mp3',thumbnail:'data/vexpaer.png' },
    { title:'AViVA - UNBREAKABLE.mp3',singer:'NULL',audio:'music/AViVA - UNBREAKABLE.mp3',thumbnail:'data/vexpaer.png' },
    { title:'AViVA - WICKED.mp3',singer:'NULL',audio:'music/AViVA - WICKED.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Axero - Trip.mp3',singer:'NULL',audio:'music/Axero - Trip.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Bahari - ＊＊＊＊＊＊ Up.mp3',singer:'NULL',audio:'music/Bahari - ＊＊＊＊＊＊ Up.mp3',thumbnail:'data/vexpaer.png' },
    { title:'BEAUZ,ThatBehavior,Luna Vexa - Bipolar.mp3',singer:'NULL',audio:'music/BEAUZ,ThatBehavior,Luna Vexa - Bipolar.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Before You Exit - Heart Like California.mp3',singer:'NULL',audio:'music/Before You Exit - Heart Like California.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Bellhouse - On a Night Like This.mp3',singer:'NULL',audio:'music/Bellhouse - On a Night Like This.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Billie Eilish - bad guy.mp3',singer:'NULL',audio:'music/Billie Eilish - bad guy.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Biscuits,ItsNoah - Drive（翻自 Oh Wonder）.mp3',singer:'NULL',audio:'music/Biscuits,ItsNoah - Drive（翻自 Oh Wonder）.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Bishop Briggs - CHAMPION.mp3',singer:'NULL',audio:'music/Bishop Briggs - CHAMPION.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Black Gryph0n,Baasik - Insane.mp3',singer:'NULL',audio:'music/Black Gryph0n,Baasik - Insane.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Blooom - Be Around.mp3',singer:'NULL',audio:'music/Blooom - Be Around.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Boyce Avenue - Love Me Like You Do.mp3',singer:'NULL',audio:'music/Boyce Avenue - Love Me Like You Do.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Brian Hyland - Itsy Bitsy Teenie Weenie Yellow Polka Dot Bikini.mp3',singer:'NULL',audio:'music/Brian Hyland - Itsy Bitsy Teenie Weenie Yellow Polka Dot Bikini.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Broiler,RAVVEL - Wild Eyes (Radio Edit).mp3',singer:'NULL',audio:'music/Broiler,RAVVEL - Wild Eyes (Radio Edit).mp3',thumbnail:'data/vexpaer.png' },
    { title:'Buckethead - Claymation Courtyard.mp3',singer:'NULL',audio:'music/Buckethead - Claymation Courtyard.mp3',thumbnail:'data/vexpaer.png' },
    { title:'BUT组合 - なんでもないや（没什么大不了）英翻《你的名字》ED.mp3',singer:'NULL',audio:'music/BUT组合 - なんでもないや（没什么大不了）英翻《你的名字》ED.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Cadmium and Jex - Not Your Baby.mp3',singer:'NULL',audio:'music/Cadmium and Jex - Not Your Baby.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Calvin Harris,Rihanna - This Is What You Came For.mp3',singer:'NULL',audio:'music/Calvin Harris,Rihanna - This Is What You Came For.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Camila Cabello - Real Friends.mp3',singer:'NULL',audio:'music/Camila Cabello - Real Friends.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Canappeco - 日和.mp3',singer:'NULL',audio:'music/Canappeco - 日和.mp3',thumbnail:'data/vexpaer.png' },
    { title:'CaptainSparklez - Revenge.mp3',singer:'NULL',audio:'music/CaptainSparklez - Revenge.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Cargo,VINAI,SCNDL - Frontier (Cargo Remix).mp3',singer:'NULL',audio:'music/Cargo,VINAI,SCNDL - Frontier (Cargo Remix).mp3',thumbnail:'data/vexpaer.png' },
    { title:'Caterina Valente - Bongo Cha Cha Cha.mp3',singer:'NULL',audio:'music/Caterina Valente - Bongo Cha Cha Cha.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Chad Sugg,Alex Goot - The One That Got Away + Use Somebody.mp3',singer:'NULL',audio:'music/Chad Sugg,Alex Goot - The One That Got Away + Use Somebody.mp3',thumbnail:'data/vexpaer.png' },
    { title:'CHANYEOL - All of me.mp3',singer:'NULL',audio:'music/CHANYEOL - All of me.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Charlie Puth - L.U.V.mp3',singer:'NULL',audio:'music/Charlie Puth - L.U.V.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Charlie Puth - Look At Me Now.mp3',singer:'NULL',audio:'music/Charlie Puth - Look At Me Now.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Charlie Puth,Selena Gomez - We Don‘t Talk Anymore.mp3',singer:'NULL',audio:'music/Charlie Puth,Selena Gomez - We Don‘t Talk Anymore.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Cheat Codes,Maggie Lindemann,CADE - Pretty Girl (Cheat Codes X CADE Remix).mp3',singer:'NULL',audio:'music/Cheat Codes,Maggie Lindemann,CADE - Pretty Girl (Cheat Codes X CADE Remix).mp3',thumbnail:'data/vexpaer.png' },
    { title:'Chris James - Make the Move.mp3',singer:'NULL',audio:'music/Chris James - Make the Move.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Cjbeards - Hurts Like Hell.mp3',singer:'NULL',audio:'music/Cjbeards - Hurts Like Hell.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Clean Bandit,Jess Glynne - Rather Be.mp3',singer:'NULL',audio:'music/Clean Bandit,Jess Glynne - Rather Be.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Cocoon - Chupee.mp3',singer:'NULL',audio:'music/Cocoon - Chupee.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Conor Matthews - Forever Right Now.mp3',singer:'NULL',audio:'music/Conor Matthews - Forever Right Now.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Conor Maynard - 7 Years.mp3',singer:'NULL',audio:'music/Conor Maynard - 7 Years.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Craig Duncan - When Johnny Comes Marching Home.mp3',singer:'NULL',audio:'music/Craig Duncan - When Johnny Comes Marching Home.mp3',thumbnail:'data/vexpaer.png' },
    { title:'cxld blxxd - Why did you enter in my life ？.mp3',singer:'NULL',audio:'music/cxld blxxd - Why did you enter in my life ？.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Daisy the Great,AJR - Record Player.mp3',singer:'NULL',audio:'music/Daisy the Great,AJR - Record Player.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Dash Berlin,Bo Bruce - Coming Home.mp3',singer:'NULL',audio:'music/Dash Berlin,Bo Bruce - Coming Home.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Daya - Bad Girl.mp3',singer:'NULL',audio:'music/Daya - Bad Girl.mp3',thumbnail:'data/vexpaer.png' },
    { title:'DEAMN - Save Me.mp3',singer:'NULL',audio:'music/DEAMN - Save Me.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Deep Chills,IVIE - Run Free (feat. IVIE).mp3',singer:'NULL',audio:'music/Deep Chills,IVIE - Run Free (feat. IVIE).mp3',thumbnail:'data/vexpaer.png' },
    { title:'Delacey - Dream It Possible.mp3',singer:'NULL',audio:'music/Delacey - Dream It Possible.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Deorro - Five Hours.mp3',singer:'NULL',audio:'music/Deorro - Five Hours.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Dirty Palm,Conor Ross,Chandler Blasé - Flowers.mp3',singer:'NULL',audio:'music/Dirty Palm,Conor Ross,Chandler Blasé - Flowers.mp3',thumbnail:'data/vexpaer.png' },
    { title:'DJ Daniel Kim - Pop Danthology 2012.mp3',singer:'NULL',audio:'music/DJ Daniel Kim - Pop Danthology 2012.mp3',thumbnail:'data/vexpaer.png' },
    { title:'DJ Isosine - Nonstop Pop 2014 Mashup.mp3',singer:'NULL',audio:'music/DJ Isosine - Nonstop Pop 2014 Mashup.mp3',thumbnail:'data/vexpaer.png' },
    { title:'DJdrybone - YouTube-Pop2017 Mashup (TakeItSlow)（DJdrybone remix）.mp3',singer:'NULL',audio:'music/DJdrybone - YouTube-Pop2017 Mashup (TakeItSlow)（DJdrybone remix）.mp3',thumbnail:'data/vexpaer.png' },
    { title:'DNMO,Sub Urban - Sick Of You.mp3',singer:'NULL',audio:'music/DNMO,Sub Urban - Sick Of You.mp3',thumbnail:'data/vexpaer.png' },
    { title:'EBIMAYO - GOODBOUNCE (Musync Edit).mp3',singer:'NULL',audio:'music/EBIMAYO - GOODBOUNCE (Musync Edit).mp3',thumbnail:'data/vexpaer.png' },
    { title:'EBIMAYO - GOODFORTUNE (Extended).mp3',singer:'NULL',audio:'music/EBIMAYO - GOODFORTUNE (Extended).mp3',thumbnail:'data/vexpaer.png' },
    { title:'EBIMAYO - GOODRAGE (Long.ver).mp3',singer:'NULL',audio:'music/EBIMAYO - GOODRAGE (Long.ver).mp3',thumbnail:'data/vexpaer.png' },
    { title:'EBIMAYO - GOODTEK (for CHUNITHM).mp3',singer:'NULL',audio:'music/EBIMAYO - GOODTEK (for CHUNITHM).mp3',thumbnail:'data/vexpaer.png' },
    { title:'EBIMAYO - GOODWORLD (Extended).mp3',singer:'NULL',audio:'music/EBIMAYO - GOODWORLD (Extended).mp3',thumbnail:'data/vexpaer.png' },
    { title:'Egzod,Maestro Chives,Neoni - Royalty.mp3',singer:'NULL',audio:'music/Egzod,Maestro Chives,Neoni - Royalty.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Ellie Goulding - Burn.mp3',singer:'NULL',audio:'music/Ellie Goulding - Burn.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Ellie Goulding - Still Falling for You.mp3',singer:'NULL',audio:'music/Ellie Goulding - Still Falling for You.mp3',thumbnail:'data/vexpaer.png' },
    { title:'ElyonCygnus - 路标-紫罗兰永恒花园ED.mp3',singer:'NULL',audio:'music/ElyonCygnus - 路标-紫罗兰永恒花园ED.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Emilee - Heaven.mp3',singer:'NULL',audio:'music/Emilee - Heaven.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Emily Vaughn - Mood.mp3',singer:'NULL',audio:'music/Emily Vaughn - Mood.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Fall Out Boy - Centuries.mp3',singer:'NULL',audio:'music/Fall Out Boy - Centuries.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Fall Out Boy - Immortals.mp3',singer:'NULL',audio:'music/Fall Out Boy - Immortals.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Fall Out Boy - My Songs Know What You Did In The Dark (Light Em Up).mp3',singer:'NULL',audio:'music/Fall Out Boy - My Songs Know What You Did In The Dark (Light Em Up).mp3',thumbnail:'data/vexpaer.png' },
    { title:'Fall Out Boy,Imagine Dragons - Radioactive In The Dark.mp3',singer:'NULL',audio:'music/Fall Out Boy,Imagine Dragons - Radioactive In The Dark.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Fiji Blue - It Takes Two.mp3',singer:'NULL',audio:'music/Fiji Blue - It Takes Two.mp3',thumbnail:'data/vexpaer.png' },
    { title:'FKJ,Tom Bailey - Drops.mp3',singer:'NULL',audio:'music/FKJ,Tom Bailey - Drops.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Fleurie,Ruslan - Take Me With You.mp3',singer:'NULL',audio:'music/Fleurie,Ruslan - Take Me With You.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Frank_Jiang - 黄昏之时（Instrumental）.mp3',singer:'NULL',audio:'music/Frank_Jiang - 黄昏之时（Instrumental）.mp3',thumbnail:'data/vexpaer.png' },
    { title:'French Montana,Swae Lee - Unforgettable.mp3',singer:'NULL',audio:'music/French Montana,Swae Lee - Unforgettable.mp3',thumbnail:'data/vexpaer.png' },
    { title:'FrogMonster - Remember Our Summer.mp3',singer:'NULL',audio:'music/FrogMonster - Remember Our Summer.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Future - Mask Off.mp3',singer:'NULL',audio:'music/Future - Mask Off.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Gabrielle Aplin,JP Cooper - Losing Me (Piano Version).mp3',singer:'NULL',audio:'music/Gabrielle Aplin,JP Cooper - Losing Me (Piano Version).mp3',thumbnail:'data/vexpaer.png' },
    { title:'Gavin DeGraw - Fire.mp3',singer:'NULL',audio:'music/Gavin DeGraw - Fire.mp3',thumbnail:'data/vexpaer.png' },
    { title:'George Michael - Careless Whisper.mp3',singer:'NULL',audio:'music/George Michael - Careless Whisper.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Gjan - 7 Billion.mp3',singer:'NULL',audio:'music/Gjan - 7 Billion.mp3',thumbnail:'data/vexpaer.png' },
    { title:'grandson - Dirty.mp3',singer:'NULL',audio:'music/grandson - Dirty.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Grant,Nevve - The Edge.mp3',singer:'NULL',audio:'music/Grant,Nevve - The Edge.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Guard - Phantom.mp3',singer:'NULL',audio:'music/Guard - Phantom.mp3',thumbnail:'data/vexpaer.png' },
    { title:'harrisonwheeler - Vacation.mp3',singer:'NULL',audio:'music/harrisonwheeler - Vacation.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Hikaru Station - Minus Zero × Synesthesia.mp3',singer:'NULL',audio:'music/Hikaru Station - Minus Zero × Synesthesia.mp3',thumbnail:'data/vexpaer.png' },
    { title:'HoneyComeBear - アキレア.mp3',singer:'NULL',audio:'music/HoneyComeBear - アキレア.mp3',thumbnail:'data/vexpaer.png' },
    { title:'HOPE-T - 夜闯秋名山（弹幕歌词版）.mp3',singer:'NULL',audio:'music/HOPE-T - 夜闯秋名山（弹幕歌词版）.mp3',thumbnail:'data/vexpaer.png' },
    { title:'HOYO-MiX - 神女劈观·唤情 Devastation and Redemption.mp3',singer:'NULL',audio:'music/HOYO-MiX - 神女劈观·唤情 Devastation and Redemption.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Idina Menzel - Let It Go (From ＂Frozen＂／Soundtrack Version).mp3',singer:'NULL',audio:'music/Idina Menzel - Let It Go (From ＂Frozen＂／Soundtrack Version).mp3',thumbnail:'data/vexpaer.png' },
    { title:'ILLENIUM,Nevve - Fractures.mp3',singer:'NULL',audio:'music/ILLENIUM,Nevve - Fractures.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Imagine Dragons - Believer (1).mp3',singer:'NULL',audio:'music/Imagine Dragons - Believer (1).mp3',thumbnail:'data/vexpaer.png' },
    { title:'Imagine Dragons - Believer.mp3',singer:'NULL',audio:'music/Imagine Dragons - Believer.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Imagine Dragons - Bones.mp3',singer:'NULL',audio:'music/Imagine Dragons - Bones.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Imagine Dragons - Radioactive.mp3',singer:'NULL',audio:'music/Imagine Dragons - Radioactive.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Imagine Dragons - Whatever It Takes.mp3',singer:'NULL',audio:'music/Imagine Dragons - Whatever It Takes.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Imagine Dragons,Broiler - Shots (Broiler Remix) (1).mp3',singer:'NULL',audio:'music/Imagine Dragons,Broiler - Shots (Broiler Remix) (1).mp3',thumbnail:'data/vexpaer.png' },
    { title:'Imagine Dragons,Broiler - Shots (Broiler Remix).mp3',singer:'NULL',audio:'music/Imagine Dragons,Broiler - Shots (Broiler Remix).mp3',thumbnail:'data/vexpaer.png' },
    { title:'Imagine Dragons,Elisa - Birds.mp3',singer:'NULL',audio:'music/Imagine Dragons,Elisa - Birds.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Imagine Dragons,JID,英雄联盟 - Enemy (from the series Arcane League of Legends).mp3',singer:'NULL',audio:'music/Imagine Dragons,JID,英雄联盟 - Enemy (from the series Arcane League of Legends).mp3',thumbnail:'data/vexpaer.png' },
    { title:'Imagine Dragons,Lil Wayne - Believer.mp3',singer:'NULL',audio:'music/Imagine Dragons,Lil Wayne - Believer.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Ingrid Michaelson - Everybody.mp3',singer:'NULL',audio:'music/Ingrid Michaelson - Everybody.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Ingrid Michaelson - Time Machine.mp3',singer:'NULL',audio:'music/Ingrid Michaelson - Time Machine.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Ingrid Michaelson,AJR - Celebrate.mp3',singer:'NULL',audio:'music/Ingrid Michaelson,AJR - Celebrate.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Inverness,Amelia Moore - Toxic.mp3',singer:'NULL',audio:'music/Inverness,Amelia Moore - Toxic.mp3',thumbnail:'data/vexpaer.png' },
    { title:'iozioz - Mask Off Aesthetic(铃铛版).mp3',singer:'NULL',audio:'music/iozioz - Mask Off Aesthetic(铃铛版).mp3',thumbnail:'data/vexpaer.png' },
    { title:'J.Fla - 2002.mp3',singer:'NULL',audio:'music/J.Fla - 2002.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Jack Stauber - buttercup.mp3',singer:'NULL',audio:'music/Jack Stauber - buttercup.mp3',thumbnail:'data/vexpaer.png' },
    { title:'James Carter,Katrine Stenbekk - Somebody Like You.mp3',singer:'NULL',audio:'music/James Carter,Katrine Stenbekk - Somebody Like You.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Jane & The Boy - Starry Eyed.mp3',singer:'NULL',audio:'music/Jane & The Boy - Starry Eyed.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Jason.c - Jason.c - Earthquake(Jason.c Extended Mix).mp3',singer:'NULL',audio:'music/Jason.c - Jason.c - Earthquake(Jason.c Extended Mix).mp3',thumbnail:'data/vexpaer.png' },
    { title:'JAWNY - Honeypie.mp3',singer:'NULL',audio:'music/JAWNY - Honeypie.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Jax - La La Land.mp3',singer:'NULL',audio:'music/Jax - La La Land.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Jenna Davis - Born for More.mp3',singer:'NULL',audio:'music/Jenna Davis - Born for More.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Jinja,KIRA - Machine Gun.mp3',singer:'NULL',audio:'music/Jinja,KIRA - Machine Gun.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Joel Adams - Please Don‘t Go.mp3',singer:'NULL',audio:'music/Joel Adams - Please Don‘t Go.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Johnny Orlando - Last Summer.mp3',singer:'NULL',audio:'music/Johnny Orlando - Last Summer.mp3',thumbnail:'data/vexpaer.png' },
    { title:'JSore - 人生苦短.mp3',singer:'NULL',audio:'music/JSore - 人生苦短.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Julia Sheer,Jon D. - Little Talks.mp3',singer:'NULL',audio:'music/Julia Sheer,Jon D. - Little Talks.mp3',thumbnail:'data/vexpaer.png' },
    { title:'KAII - ／／／.mp3',singer:'NULL',audio:'music/KAII - ／／／.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Katie Herzig - Forevermore.mp3',singer:'NULL',audio:'music/Katie Herzig - Forevermore.mp3',thumbnail:'data/vexpaer.png' },
    { title:'KBShinya - 与子同泽.mp3',singer:'NULL',audio:'music/KBShinya - 与子同泽.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Kedam - Happiness.mp3',singer:'NULL',audio:'music/Kedam - Happiness.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Kedam - Shy Girl.mp3',singer:'NULL',audio:'music/Kedam - Shy Girl.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Kelly Clarkson - Stronger (What Doesn‘t Kill You).mp3',singer:'NULL',audio:'music/Kelly Clarkson - Stronger (What Doesn‘t Kill You).mp3',thumbnail:'data/vexpaer.png' },
    { title:'Kina,Adriana Proenza - Can We Kiss Forever？.mp3',singer:'NULL',audio:'music/Kina,Adriana Proenza - Can We Kiss Forever？.mp3',thumbnail:'data/vexpaer.png' },
    { title:'King Gnu - 白日.mp3',singer:'NULL',audio:'music/King Gnu - 白日.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Lady Gaga - Poker Face.mp3',singer:'NULL',audio:'music/Lady Gaga - Poker Face.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Lauv,Julia Michaels - There‘s No Way.mp3',singer:'NULL',audio:'music/Lauv,Julia Michaels - There‘s No Way.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Layto - Beauty.mp3',singer:'NULL',audio:'music/Layto - Beauty.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Layto - Houndin.mp3',singer:'NULL',audio:'music/Layto - Houndin.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Layto,Neoni - Ghost Town.mp3',singer:'NULL',audio:'music/Layto,Neoni - Ghost Town.mp3',thumbnail:'data/vexpaer.png' },
    { title:'LeaF - 狂喜蘭舞 (Long Ver.).mp3',singer:'NULL',audio:'music/LeaF - 狂喜蘭舞 (Long Ver.).mp3',thumbnail:'data/vexpaer.png' },
    { title:'Lefty Hand Cream - シュガーソングとビターステップ.mp3',singer:'NULL',audio:'music/Lefty Hand Cream - シュガーソングとビターステップ.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Lenka - Unique.mp3',singer:'NULL',audio:'music/Lenka - Unique.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Lenka,Nick Howard - Stuck Like Glue.mp3',singer:'NULL',audio:'music/Lenka,Nick Howard - Stuck Like Glue.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Lindsey Stirling - Artemis.mp3',singer:'NULL',audio:'music/Lindsey Stirling - Artemis.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Lindsey Stirling - Guardian.mp3',singer:'NULL',audio:'music/Lindsey Stirling - Guardian.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Lindsey Stirling - Masquerade.mp3',singer:'NULL',audio:'music/Lindsey Stirling - Masquerade.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Lindsey Stirling - Roundtable Rival.mp3',singer:'NULL',audio:'music/Lindsey Stirling - Roundtable Rival.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Lindsey Stirling - The Arena.mp3',singer:'NULL',audio:'music/Lindsey Stirling - The Arena.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Lindsey Stirling - Til the Light Goes Out.mp3',singer:'NULL',audio:'music/Lindsey Stirling - Til the Light Goes Out.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Lindsey Stirling - Underground.mp3',singer:'NULL',audio:'music/Lindsey Stirling - Underground.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Lindsey Stirling,Kiesza - What You’re Made Of (feat. Kiesza) (From “Azur Lane” Original Video Game Soundtrack).mp3',singer:'NULL',audio:'music/Lindsey Stirling,Kiesza - What You’re Made Of (feat. Kiesza) (From “Azur Lane” Original Video Game Soundtrack).mp3',thumbnail:'data/vexpaer.png' },
    { title:'Lindsey Stirling,Mako - Lose You Now (Acoustic).mp3',singer:'NULL',audio:'music/Lindsey Stirling,Mako - Lose You Now (Acoustic).mp3',thumbnail:'data/vexpaer.png' },
    { title:'Lindsey Stirling,Mako - Lose You Now.mp3',singer:'NULL',audio:'music/Lindsey Stirling,Mako - Lose You Now.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Lindsey Stirling,Vicetone - Afterglow (Bonus Track).mp3',singer:'NULL',audio:'music/Lindsey Stirling,Vicetone - Afterglow (Bonus Track).mp3',thumbnail:'data/vexpaer.png' },
    { title:'LiSA - unlasting (THE FIRST TAKE Studio Ver.).mp3',singer:'NULL',audio:'music/LiSA - unlasting (THE FIRST TAKE Studio Ver.).mp3',thumbnail:'data/vexpaer.png' },
    { title:'Loren Gray - Queen.mp3',singer:'NULL',audio:'music/Loren Gray - Queen.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Louisa Wendorff,Devin Dawson - Blank Space  Style (feat. Devin Dawson).mp3',singer:'NULL',audio:'music/Louisa Wendorff,Devin Dawson - Blank Space  Style (feat. Devin Dawson).mp3',thumbnail:'data/vexpaer.png' },
    { title:'Lounge Noir - Payphone (I‘m At a Payphone).mp3',singer:'NULL',audio:'music/Lounge Noir - Payphone (I‘m At a Payphone).mp3',thumbnail:'data/vexpaer.png' },
    { title:'Loïc Nottet - Hungry Heart.mp3',singer:'NULL',audio:'music/Loïc Nottet - Hungry Heart.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Loïc Nottet - Million Eyes.mp3',singer:'NULL',audio:'music/Loïc Nottet - Million Eyes.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Lucy Schwartz - I Want The Sky.mp3',singer:'NULL',audio:'music/Lucy Schwartz - I Want The Sky.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Luis Fonsi,Daddy Yankee,Justin Bieber - Despacito (Remix).mp3',singer:'NULL',audio:'music/Luis Fonsi,Daddy Yankee,Justin Bieber - Despacito (Remix).mp3',thumbnail:'data/vexpaer.png' },
    { title:'Luvbug - Best Is Yet To Come.mp3',singer:'NULL',audio:'music/Luvbug - Best Is Yet To Come.mp3',thumbnail:'data/vexpaer.png' },
    { title:'m-taku - Komorebi.mp3',singer:'NULL',audio:'music/m-taku - Komorebi.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Macklemore,Skylar Grey - Glorious.mp3',singer:'NULL',audio:'music/Macklemore,Skylar Grey - Glorious.mp3',thumbnail:'data/vexpaer.png' },
    { title:'MADILYN - Galway Girl.mp3',singer:'NULL',audio:'music/MADILYN - Galway Girl.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Madilyn Paige - Someone You Loved.mp3',singer:'NULL',audio:'music/Madilyn Paige - Someone You Loved.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Magentium - Monodevania.mp3',singer:'NULL',audio:'music/Magentium - Monodevania.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Manafest - Edge Of My Life.mp3',singer:'NULL',audio:'music/Manafest - Edge Of My Life.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Marc Sean - What Makes You Beautiful.mp3',singer:'NULL',audio:'music/Marc Sean - What Makes You Beautiful.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Maroon 5 - Animals.mp3',singer:'NULL',audio:'music/Maroon 5 - Animals.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Maroon 5 - In Your Pocket.mp3',singer:'NULL',audio:'music/Maroon 5 - In Your Pocket.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Maroon 5 - Maps.mp3',singer:'NULL',audio:'music/Maroon 5 - Maps.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Maroon 5 - Sugar.mp3',singer:'NULL',audio:'music/Maroon 5 - Sugar.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Maroon 5,Christina Aguilera - Moves Like Jagger.mp3',singer:'NULL',audio:'music/Maroon 5,Christina Aguilera - Moves Like Jagger.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Maroon 5,Gwen Stefani - My Heart Is Open.mp3',singer:'NULL',audio:'music/Maroon 5,Gwen Stefani - My Heart Is Open.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Martin Jensen - Solo Dance.mp3',singer:'NULL',audio:'music/Martin Jensen - Solo Dance.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Matilda - Illusion.mp3',singer:'NULL',audio:'music/Matilda - Illusion.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Mes - Palette (English ver.)（翻自 巡音流歌）.mp3',singer:'NULL',audio:'music/Mes - Palette (English ver.)（翻自 巡音流歌）.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Mes,Tuno桐音 - Tides.mp3',singer:'NULL',audio:'music/Mes,Tuno桐音 - Tides.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Metrixx - Play Date.mp3',singer:'NULL',audio:'music/Metrixx - Play Date.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Michael Jackson - Heal the World.mp3',singer:'NULL',audio:'music/Michael Jackson - Heal the World.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Michael Schulte - For a Second.mp3',singer:'NULL',audio:'music/Michael Schulte - For a Second.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Mike Candys,Maury - Miracles (Radio Edit).mp3',singer:'NULL',audio:'music/Mike Candys,Maury - Miracles (Radio Edit).mp3',thumbnail:'data/vexpaer.png' },
    { title:'Mike Tompkins,Dumbfoundead - Dark Horse ／ Jaguar.mp3',singer:'NULL',audio:'music/Mike Tompkins,Dumbfoundead - Dark Horse ／ Jaguar.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Mindy Gledhill - Trouble No More.mp3',singer:'NULL',audio:'music/Mindy Gledhill - Trouble No More.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Missio - I See You.mp3',singer:'NULL',audio:'music/Missio - I See You.mp3',thumbnail:'data/vexpaer.png' },
    { title:'MKJ - Time (Official).mp3',singer:'NULL',audio:'music/MKJ - Time (Official).mp3',thumbnail:'data/vexpaer.png' },
    { title:'MOCCA - I Remember.mp3',singer:'NULL',audio:'music/MOCCA - I Remember.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Mokita - colorblind.mp3',singer:'NULL',audio:'music/Mokita - colorblind.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Monogem - Wild.mp3',singer:'NULL',audio:'music/Monogem - Wild.mp3',thumbnail:'data/vexpaer.png' },
    { title:'MoreanP - Ephemeral Memories.mp3',singer:'NULL',audio:'music/MoreanP - Ephemeral Memories.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Mr FijiWiji,Laura Brehm,AgNo3 - Pure Sunlight.mp3',singer:'NULL',audio:'music/Mr FijiWiji,Laura Brehm,AgNo3 - Pure Sunlight.mp3',thumbnail:'data/vexpaer.png' },
    { title:'MÖWE,Bright Sparks - Your Skin.mp3',singer:'NULL',audio:'music/MÖWE,Bright Sparks - Your Skin.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Naaz - SADBOY (Original Mix).mp3',singer:'NULL',audio:'music/Naaz - SADBOY (Original Mix).mp3',thumbnail:'data/vexpaer.png' },
    { title:'Nao‘ymt - Someday I Will Die.mp3',singer:'NULL',audio:'music/Nao‘ymt - Someday I Will Die.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Neon Tribe,Katelyn Tarver - Planez (Neon Tribe Remix).mp3',singer:'NULL',audio:'music/Neon Tribe,Katelyn Tarver - Planez (Neon Tribe Remix).mp3',thumbnail:'data/vexpaer.png' },
    { title:'Neoni - OUTLAW.mp3',singer:'NULL',audio:'music/Neoni - OUTLAW.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Neovaii - Labels.mp3',singer:'NULL',audio:'music/Neovaii - Labels.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Neovaii - Serenity.mp3',singer:'NULL',audio:'music/Neovaii - Serenity.mp3',thumbnail:'data/vexpaer.png' },
    { title:'NLSN,Lisa Rowe - Blue in My Eyes.mp3',singer:'NULL',audio:'music/NLSN,Lisa Rowe - Blue in My Eyes.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Oceans - Cold Ain‘t For Me.mp3',singer:'NULL',audio:'music/Oceans - Cold Ain‘t For Me.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Oh The Larceny - This Is It.mp3',singer:'NULL',audio:'music/Oh The Larceny - This Is It.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Olly Murs - Somebody New.mp3',singer:'NULL',audio:'music/Olly Murs - Somebody New.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Olly Murs - That Girl.mp3',singer:'NULL',audio:'music/Olly Murs - That Girl.mp3',thumbnail:'data/vexpaer.png' },
    { title:'OneRepublic - Counting Stars (1).mp3',singer:'NULL',audio:'music/OneRepublic - Counting Stars (1).mp3',thumbnail:'data/vexpaer.png' },
    { title:'OneRepublic - Counting Stars.mp3',singer:'NULL',audio:'music/OneRepublic - Counting Stars.mp3',thumbnail:'data/vexpaer.png' },
    { title:'OutaMatic,Maddie Wilson,Madilyn Paige - Locked Away.mp3',singer:'NULL',audio:'music/OutaMatic,Maddie Wilson,Madilyn Paige - Locked Away.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Owl City - All My Friends.mp3',singer:'NULL',audio:'music/Owl City - All My Friends.mp3',thumbnail:'data/vexpaer.png' },
    { title:'OYRH - Saika（古筝版）.mp3',singer:'NULL',audio:'music/OYRH - Saika（古筝版）.mp3',thumbnail:'data/vexpaer.png' },
    { title:'OYRH - 王者荣耀（电音版）.mp3',singer:'NULL',audio:'music/OYRH - 王者荣耀（电音版）.mp3',thumbnail:'data/vexpaer.png' },
    { title:'P!nk - Just Like Fire (From the Original Motion Picture ＂Alice Through The Looking Glass＂).mp3',singer:'NULL',audio:'music/P!nk - Just Like Fire (From the Original Motion Picture ＂Alice Through The Looking Glass＂).mp3',thumbnail:'data/vexpaer.png' },
    { title:'PhaseSecond - SummerRain.mp3',singer:'NULL',audio:'music/PhaseSecond - SummerRain.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Pháo,KAIZ - 2 Phút Hơn (KAIZ Remix).mp3',singer:'NULL',audio:'music/Pháo,KAIZ - 2 Phút Hơn (KAIZ Remix).mp3',thumbnail:'data/vexpaer.png' },
    { title:'PREP - On and On.mp3',singer:'NULL',audio:'music/PREP - On and On.mp3',thumbnail:'data/vexpaer.png' },
    { title:'PRODTAG,Ental Miller - RACE (feat. Ental Miller).mp3',singer:'NULL',audio:'music/PRODTAG,Ental Miller - RACE (feat. Ental Miller).mp3',thumbnail:'data/vexpaer.png' },
    { title:'Professor Green - In The Shadow Of The Sun.mp3',singer:'NULL',audio:'music/Professor Green - In The Shadow Of The Sun.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Purity Ring - flood on the floor.mp3',singer:'NULL',audio:'music/Purity Ring - flood on the floor.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Push Baby - Mama‘s House.mp3',singer:'NULL',audio:'music/Push Baby - Mama‘s House.mp3',thumbnail:'data/vexpaer.png' },
    { title:'PØRPEL,Marcus & Martinus - Heartbeat (Nightcore) [PØRPEL Remix].mp3',singer:'NULL',audio:'music/PØRPEL,Marcus & Martinus - Heartbeat (Nightcore) [PØRPEL Remix].mp3',thumbnail:'data/vexpaer.png' },
    { title:'Q;indivi - Wedding March Part.2~The Bridal Chorus From The Opera Lohengrin~.mp3',singer:'NULL',audio:'music/Q;indivi - Wedding March Part.2~The Bridal Chorus From The Opera Lohengrin~.mp3',thumbnail:'data/vexpaer.png' },
    { title:'R3HAB - Sakura.mp3',singer:'NULL',audio:'music/R3HAB - Sakura.mp3',thumbnail:'data/vexpaer.png' },
    { title:'R7CKY - 夢燈籠 (R7CKY 你的名字 Mix).mp3',singer:'NULL',audio:'music/R7CKY - 夢燈籠 (R7CKY 你的名字 Mix).mp3',thumbnail:'data/vexpaer.png' },
    { title:'Rachel Platten - Fight Song.mp3',singer:'NULL',audio:'music/Rachel Platten - Fight Song.mp3',thumbnail:'data/vexpaer.png' },
    { title:'RADI8,Akie秋绘,夏璃夜 - IA-アスノヨゾラ哨戒班／明日的夜空哨戒班（REGG$HOTS ／ Akie秋绘 ／ 夏璃夜 remix）.mp3',singer:'NULL',audio:'music/RADI8,Akie秋绘,夏璃夜 - IA-アスノヨゾラ哨戒班／明日的夜空哨戒班（REGG$HOTS ／ Akie秋绘 ／ 夏璃夜 remix）.mp3',thumbnail:'data/vexpaer.png' },
    { title:'RADWIMPS - 愛にできることはまだあるかい.mp3',singer:'NULL',audio:'music/RADWIMPS - 愛にできることはまだあるかい.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Rag‘N‘Bone Man - Skin.mp3',singer:'NULL',audio:'music/Rag‘N‘Bone Man - Skin.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Reboost - Little More.mp3',singer:'NULL',audio:'music/Reboost - Little More.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Relient K - Can‘t Complain.mp3',singer:'NULL',audio:'music/Relient K - Can‘t Complain.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Reol,ギガP - No title.mp3',singer:'NULL',audio:'music/Reol,ギガP - No title.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Reyko - Don‘t Mention My Name.mp3',singer:'NULL',audio:'music/Reyko - Don‘t Mention My Name.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Reyko - Lose Myself.mp3',singer:'NULL',audio:'music/Reyko - Lose Myself.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Reyko - Set You Free.mp3',singer:'NULL',audio:'music/Reyko - Set You Free.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Reyko - Spinning over You.mp3',singer:'NULL',audio:'music/Reyko - Spinning over You.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Robert Delong,K.Flay - Favorite Color Is Blue.mp3',singer:'NULL',audio:'music/Robert Delong,K.Flay - Favorite Color Is Blue.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Robin Skouteris - Pop Love 2014.mp3',singer:'NULL',audio:'music/Robin Skouteris - Pop Love 2014.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Robin Skouteris - PopLove (2012).mp3',singer:'NULL',audio:'music/Robin Skouteris - PopLove (2012).mp3',thumbnail:'data/vexpaer.png' },
    { title:'Rudimental,Jess Glynne,Macklemore - These Days.mp3',singer:'NULL',audio:'music/Rudimental,Jess Glynne,Macklemore - These Days.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Rudy Mancuso - Musical Fiction.mp3',singer:'NULL',audio:'music/Rudy Mancuso - Musical Fiction.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Sachi,Nika - Shelter.mp3',singer:'NULL',audio:'music/Sachi,Nika - Shelter.mp3',thumbnail:'data/vexpaer.png' },
    { title:'SAFIA - Counting Sheep.mp3',singer:'NULL',audio:'music/SAFIA - Counting Sheep.mp3',thumbnail:'data/vexpaer.png' },
    { title:'SAM F,JVZEL - Zone (feat. JVZEL) (Clean Mix).mp3',singer:'NULL',audio:'music/SAM F,JVZEL - Zone (feat. JVZEL) (Clean Mix).mp3',thumbnail:'data/vexpaer.png' },
    { title:'SAM F,Malcolm Anthony - ＊＊＊＊ Wit A G.mp3',singer:'NULL',audio:'music/SAM F,Malcolm Anthony - ＊＊＊＊ Wit A G.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Sam Fischer,Demi Lovato - What Other People Say.mp3',singer:'NULL',audio:'music/Sam Fischer,Demi Lovato - What Other People Say.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Sandra Lyng - Don‘t Care.mp3',singer:'NULL',audio:'music/Sandra Lyng - Don‘t Care.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Sasha Alex Sloan - Dancing With Your Ghost.mp3',singer:'NULL',audio:'music/Sasha Alex Sloan - Dancing With Your Ghost.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Savannah Sgro - Moody.mp3',singer:'NULL',audio:'music/Savannah Sgro - Moody.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Se-U-Ra - Igallta.mp3',singer:'NULL',audio:'music/Se-U-Ra - Igallta.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Seven Lions,Said The Sky,ILLENIUM - Rush Over Me.mp3',singer:'NULL',audio:'music/Seven Lions,Said The Sky,ILLENIUM - Rush Over Me.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Shakira - Try Everything.mp3',singer:'NULL',audio:'music/Shakira - Try Everything.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Shawn Hook,Vanessa Hudgens - Reminding Me.mp3',singer:'NULL',audio:'music/Shawn Hook,Vanessa Hudgens - Reminding Me.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Shawn Mendes,Camila Cabello - Señorita.mp3',singer:'NULL',audio:'music/Shawn Mendes,Camila Cabello - Señorita.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Shoffy - Cool Again.mp3',singer:'NULL',audio:'music/Shoffy - Cool Again.mp3',thumbnail:'data/vexpaer.png' },
    { title:'SHY Martin - Forget to Forget.mp3',singer:'NULL',audio:'music/SHY Martin - Forget to Forget.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Sia - Cheap Thrills (1).mp3',singer:'NULL',audio:'music/Sia - Cheap Thrills (1).mp3',thumbnail:'data/vexpaer.png' },
    { title:'Sia - Cheap Thrills.mp3',singer:'NULL',audio:'music/Sia - Cheap Thrills.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Sigrid - Mirror.mp3',singer:'NULL',audio:'music/Sigrid - Mirror.mp3',thumbnail:'data/vexpaer.png' },
    { title:'SKOTT - Mermaid.mp3',singer:'NULL',audio:'music/SKOTT - Mermaid.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Sky.High - 18：49.mp3',singer:'NULL',audio:'music/Sky.High - 18：49.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Softly - Girl‘s Talk.mp3',singer:'NULL',audio:'music/Softly - Girl‘s Talk.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Softly - up to you.mp3',singer:'NULL',audio:'music/Softly - up to you.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Sophia Ayana - Heartbreak Hotel.mp3',singer:'NULL',audio:'music/Sophia Ayana - Heartbreak Hotel.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Sou - 7150日.mp3',singer:'NULL',audio:'music/Sou - 7150日.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Sou,いすぼくろ - 命ばっかり.mp3',singer:'NULL',audio:'music/Sou,いすぼくろ - 命ばっかり.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Steerner,Martell - Sky (Radio Edit).mp3',singer:'NULL',audio:'music/Steerner,Martell - Sky (Radio Edit).mp3',thumbnail:'data/vexpaer.png' },
    { title:'Stevie Hoang - Before You Break My Heart.mp3',singer:'NULL',audio:'music/Stevie Hoang - Before You Break My Heart.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Strictlyviolin荀博 - Normal No More.mp3',singer:'NULL',audio:'music/Strictlyviolin荀博 - Normal No More.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Sub Urban - KMS.mp3',singer:'NULL',audio:'music/Sub Urban - KMS.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Sub Urban - Spring Fever.mp3',singer:'NULL',audio:'music/Sub Urban - Spring Fever.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Sub Urban,REI AMI - Freak (feat. REI AMI).mp3',singer:'NULL',audio:'music/Sub Urban,REI AMI - Freak (feat. REI AMI).mp3',thumbnail:'data/vexpaer.png' },
    { title:'Summer Ice - Env-PneumaticTokyo (3D Bootleg)（Summer Ice remix）.mp3',singer:'NULL',audio:'music/Summer Ice - Env-PneumaticTokyo (3D Bootleg)（Summer Ice remix）.mp3',thumbnail:'data/vexpaer.png' },
    { title:'SunsetRay - Chronos Collapse - La Campanella.mp3',singer:'NULL',audio:'music/SunsetRay - Chronos Collapse - La Campanella.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Tails,Inverness,Nevve - Skeleton (feat. Nevve).mp3',singer:'NULL',audio:'music/Tails,Inverness,Nevve - Skeleton (feat. Nevve).mp3',thumbnail:'data/vexpaer.png' },
    { title:'Taylor Swift,Elvira - willow (dancing witch version (Elvira remix)).mp3',singer:'NULL',audio:'music/Taylor Swift,Elvira - willow (dancing witch version (Elvira remix)).mp3',thumbnail:'data/vexpaer.png' },
    { title:'Taylor Thrash - Oh Hello.mp3',singer:'NULL',audio:'music/Taylor Thrash - Oh Hello.mp3',thumbnail:'data/vexpaer.png' },
    { title:'teamwork,Nina Nesbitt,AJ Mitchell - Afterhours.mp3',singer:'NULL',audio:'music/teamwork,Nina Nesbitt,AJ Mitchell - Afterhours.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Tessa Violet - Crush.mp3',singer:'NULL',audio:'music/Tessa Violet - Crush.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Tez Cadey - Seve.mp3',singer:'NULL',audio:'music/Tez Cadey - Seve.mp3',thumbnail:'data/vexpaer.png' },
    { title:'The Cab - Lock Me Up.mp3',singer:'NULL',audio:'music/The Cab - Lock Me Up.mp3',thumbnail:'data/vexpaer.png' },
    { title:'The Cartoons - Witch Doctor.mp3',singer:'NULL',audio:'music/The Cartoons - Witch Doctor.mp3',thumbnail:'data/vexpaer.png' },
    { title:'The Chainsmokers,Aash Mehta,Halsey - Clsr (Aash Mehta Flip).mp3',singer:'NULL',audio:'music/The Chainsmokers,Aash Mehta,Halsey - Clsr (Aash Mehta Flip).mp3',thumbnail:'data/vexpaer.png' },
    { title:'The Downtown Fiction - I Just Wanna Run.mp3',singer:'NULL',audio:'music/The Downtown Fiction - I Just Wanna Run.mp3',thumbnail:'data/vexpaer.png' },
    { title:'The Glitch Mob,Mako,The Word Alive - RISE.mp3',singer:'NULL',audio:'music/The Glitch Mob,Mako,The Word Alive - RISE.mp3',thumbnail:'data/vexpaer.png' },
    { title:'The Kinks - Supersonic Rocket Ship.mp3',singer:'NULL',audio:'music/The Kinks - Supersonic Rocket Ship.mp3',thumbnail:'data/vexpaer.png' },
    { title:'The Score - Head Up.mp3',singer:'NULL',audio:'music/The Score - Head Up.mp3',thumbnail:'data/vexpaer.png' },
    { title:'The Script,will.i.am - Hall of Fame.mp3',singer:'NULL',audio:'music/The Script,will.i.am - Hall of Fame.mp3',thumbnail:'data/vexpaer.png' },
    { title:'The Stupendium - Rest Employed.mp3',singer:'NULL',audio:'music/The Stupendium - Rest Employed.mp3',thumbnail:'data/vexpaer.png' },
    { title:'The Tech Thieves - Bang!.mp3',singer:'NULL',audio:'music/The Tech Thieves - Bang!.mp3',thumbnail:'data/vexpaer.png' },
    { title:'The Tech Thieves - Heart Made of Stone.mp3',singer:'NULL',audio:'music/The Tech Thieves - Heart Made of Stone.mp3',thumbnail:'data/vexpaer.png' },
    { title:'The Tech Thieves - Lighthouse.mp3',singer:'NULL',audio:'music/The Tech Thieves - Lighthouse.mp3',thumbnail:'data/vexpaer.png' },
    { title:'TheFatRat,Everen Maxwell,Lindsey Stirling - Warbringer.mp3',singer:'NULL',audio:'music/TheFatRat,Everen Maxwell,Lindsey Stirling - Warbringer.mp3',thumbnail:'data/vexpaer.png' },
    { title:'TheFatRat,Laura Brehm - MAYDAY.mp3',singer:'NULL',audio:'music/TheFatRat,Laura Brehm - MAYDAY.mp3',thumbnail:'data/vexpaer.png' },
    { title:'ThimLife,Bibiane Z - Another You.mp3',singer:'NULL',audio:'music/ThimLife,Bibiane Z - Another You.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Tobu - Higher.mp3',singer:'NULL',audio:'music/Tobu - Higher.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Twinfield,初音ミク - Bugfix Girl.mp3',singer:'NULL',audio:'music/Twinfield,初音ミク - Bugfix Girl.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Tyler Ward - Baby(Acoustic Version).mp3',singer:'NULL',audio:'music/Tyler Ward - Baby(Acoustic Version).mp3',thumbnail:'data/vexpaer.png' },
    { title:'TYMA,MADILYN - Wake Me Up (TYMA Remix).mp3',singer:'NULL',audio:'music/TYMA,MADILYN - Wake Me Up (TYMA Remix).mp3',thumbnail:'data/vexpaer.png' },
    { title:'Unlike Pluto - 8 Legged Dreams.mp3',singer:'NULL',audio:'music/Unlike Pluto - 8 Legged Dreams.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Unlike Pluto - FMO.mp3',singer:'NULL',audio:'music/Unlike Pluto - FMO.mp3',thumbnail:'data/vexpaer.png' },
    { title:'V.A. - MrMusic(原唱x96猫) (双声道版).mp3',singer:'NULL',audio:'music/V.A. - MrMusic(原唱x96猫) (双声道版).mp3',thumbnail:'data/vexpaer.png' },
    { title:'Various Artists - Going Home.mp3',singer:'NULL',audio:'music/Various Artists - Going Home.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Various Artists - She taught me how to yodel(约德尔调).mp3',singer:'NULL',audio:'music/Various Artists - She taught me how to yodel(约德尔调).mp3',thumbnail:'data/vexpaer.png' },
    { title:'Various Artists,Jimmy Fallon - We Didn‘t Start the Fire.mp3',singer:'NULL',audio:'music/Various Artists,Jimmy Fallon - We Didn‘t Start the Fire.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Veezy - Name.mp3',singer:'NULL',audio:'music/Veezy - Name.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Viceroy,Patrick Baker - Next Escape.mp3',singer:'NULL',audio:'music/Viceroy,Patrick Baker - Next Escape.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Vicetone - Walk Thru Fire.mp3',singer:'NULL',audio:'music/Vicetone - Walk Thru Fire.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Virtual Riot - Energy Drink.mp3',singer:'NULL',audio:'music/Virtual Riot - Energy Drink.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Walk off the Earth - Fifth Avenue.mp3',singer:'NULL',audio:'music/Walk off the Earth - Fifth Avenue.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Walk off the Earth - Old Town Road.mp3',singer:'NULL',audio:'music/Walk off the Earth - Old Town Road.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Wham! - Careless Whisper.mp3',singer:'NULL',audio:'music/Wham! - Careless Whisper.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Whethan,Ashe - Can‘t Hide.mp3',singer:'NULL',audio:'music/Whethan,Ashe - Can‘t Hide.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Why Mona,Unlike Pluto - Oops!... I Did It Again (feat. Unlike Pluto).mp3',singer:'NULL',audio:'music/Why Mona,Unlike Pluto - Oops!... I Did It Again (feat. Unlike Pluto).mp3',thumbnail:'data/vexpaer.png' },
    { title:'Wonderful Humans - Don‘t You.mp3',singer:'NULL',audio:'music/Wonderful Humans - Don‘t You.mp3',thumbnail:'data/vexpaer.png' },
    { title:'XYLØ - Yes & No.mp3',singer:'NULL',audio:'music/XYLØ - Yes & No.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Young Summer - Heart In Slo Mo.mp3',singer:'NULL',audio:'music/Young Summer - Heart In Slo Mo.mp3',thumbnail:'data/vexpaer.png' },
    { title:'Yunomi - Yunomix Vol. 3.5.mp3',singer:'NULL',audio:'music/Yunomi - Yunomix Vol. 3.5.mp3',thumbnail:'data/vexpaer.png' },
    { title:'伊東歌詞太郎 - 空想フォレスト.mp3',singer:'NULL',audio:'music/伊東歌詞太郎 - 空想フォレスト.mp3',thumbnail:'data/vexpaer.png' },
    { title:'佐天Tamako - さよならだけが人生だ.mp3',singer:'NULL',audio:'music/佐天Tamako - さよならだけが人生だ.mp3',thumbnail:'data/vexpaer.png' },
    { title:'佐天Tamako - インタビュア／Interviewer Piano ver.mp3',singer:'NULL',audio:'music/佐天Tamako - インタビュア／Interviewer Piano ver.mp3',thumbnail:'data/vexpaer.png' },
    { title:'土星皇家交响乐团,John Williams - 帝国进行曲（The Imperial March）（Darth Vader Theme）.mp3',singer:'NULL',audio:'music/土星皇家交响乐团,John Williams - 帝国进行曲（The Imperial March）（Darth Vader Theme）.mp3',thumbnail:'data/vexpaer.png' },
    { title:'奇然,沈谧仁 - 琵琶行.mp3',singer:'NULL',audio:'music/奇然,沈谧仁 - 琵琶行.mp3',thumbnail:'data/vexpaer.png' },
    { title:'接个吻，开一枪 - 烟袋斜街.mp3',singer:'NULL',audio:'music/接个吻，开一枪 - 烟袋斜街.mp3',thumbnail:'data/vexpaer.png' },
    { title:'接个吻，开一枪 - 田子坊.mp3',singer:'NULL',audio:'music/接个吻，开一枪 - 田子坊.mp3',thumbnail:'data/vexpaer.png' },
    { title:'接个吻，开一枪,CLARE - Beijing.mp3',singer:'NULL',audio:'music/接个吻，开一枪,CLARE - Beijing.mp3',thumbnail:'data/vexpaer.png' },
    { title:'故渊 - Ed Sheeran ／ Anne-Caroline Joy ／ Dua Lipa ／ Selena Gomez ／ Avicii-BEST MELODIES of 2017 & 2018（piano roll）（樱岛麻衣学姐 remix）.mp3',singer:'NULL',audio:'music/故渊 - Ed Sheeran ／ Anne-Caroline Joy ／ Dua Lipa ／ Selena Gomez ／ Avicii-BEST MELODIES of 2017 & 2018（piano roll）（樱岛麻衣学姐 remix）.mp3',thumbnail:'data/vexpaer.png' },
    { title:'新社会人,wis降调 - 天ノ弱 (Piano Ver.)(双声道).mp3',singer:'NULL',audio:'music/新社会人,wis降调 - 天ノ弱 (Piano Ver.)(双声道).mp3',thumbnail:'data/vexpaer.png' },
    { title:'杨和苏KeyNG - 大反派.mp3',singer:'NULL',audio:'music/杨和苏KeyNG - 大反派.mp3',thumbnail:'data/vexpaer.png' },
    { title:'杨和苏KeyNG - 小丑女.mp3',singer:'NULL',audio:'music/杨和苏KeyNG - 小丑女.mp3',thumbnail:'data/vexpaer.png' },
    { title:'桃子毛毛桑 - まふまふ ／ 赤ティン-镜花水月 纯双声道（桃子毛毛桑 ／ まふまふ ／ 赤ティン remix）.mp3',singer:'NULL',audio:'music/桃子毛毛桑 - まふまふ ／ 赤ティン-镜花水月 纯双声道（桃子毛毛桑 ／ まふまふ ／ 赤ティン remix）.mp3',thumbnail:'data/vexpaer.png' },
    { title:'米白,茶查叉 - 瞬き.mp3',singer:'NULL',audio:'music/米白,茶查叉 - 瞬き.mp3',thumbnail:'data/vexpaer.png' },
    { title:'英雄联盟 - Welcome to Planet Urf.mp3',singer:'NULL',audio:'music/英雄联盟 - Welcome to Planet Urf.mp3',thumbnail:'data/vexpaer.png' },
    { title:'蜡笔小心 - 不普通的普通女孩.mp3',singer:'NULL',audio:'music/蜡笔小心 - 不普通的普通女孩.mp3',thumbnail:'data/vexpaer.png' },
    { title:'谦 - TK from 凛として時雨-Unravel（双声道版／周深&TK）（谦 remix）.mp3',singer:'NULL',audio:'music/谦 - TK from 凛として時雨-Unravel（双声道版／周深&TK）（谦 remix）.mp3',thumbnail:'data/vexpaer.png' },
    { title:'费玉清 - 一剪梅.mp3',singer:'NULL',audio:'music/费玉清 - 一剪梅.mp3',thumbnail:'data/vexpaer.png' },
    { title:'赵雷 - 成都.mp3',singer:'NULL',audio:'music/赵雷 - 成都.mp3',thumbnail:'data/vexpaer.png' },
    { title:'音阙诗听,赵方婧 - 芒种.mp3',singer:'NULL',audio:'music/音阙诗听,赵方婧 - 芒种.mp3',thumbnail:'data/vexpaer.png' },
    
];